### ISSUE TITLE
Map writer: filter large relations / ways

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#1019]
Some maps take very long time to build and according to this [forum discussion](https://groups.google.com/forum/#!topic/mapsforge-dev/S0tCh3r3tEA) the cause could be some extremely large relations / ways.

We can explore if there is the possibility the map-writer to detect them and provide an option to filter such large element structures.

**Comment by ludwigb** [comment]
The problem I see with this is that it might result in somewhat arbitrary
maps if we filter out data based on its size.

E.g. a small forest will be included, but a large forested area will not be
as it exceeds the data limit. As a map user I would forgive a map if a
small grove of forests was not in the map, but would find it confusing if a
large forest was not there.

**Comment by boldtrn** [comment]
> E.g. a small forest will be included, but a large forested area will not be
as it exceeds the data limit.

Yes this is true, we might have to filter this a bit more, like every place=island with more than 100000 nodes or something like this. We have to choose a number of nodes that is clearly exceeding any reasonable size. If we filter out any relation, we should log this clearly and we should check the logs from time to time what relations are actually filtered and if we filter a forest, that should stay in the map, we can still think about what we can do.

Also because I think that the slowdown happens because of "is in polygon" checks, we could also use actual area as a second parameter, like if more than 100000 nodes and area larger than some km².

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
