### ISSUE TITLE
London missing from map at zoom level 7 using either InternalRenderTheme

### ISSUE THREAD

**Issue by JackPGreen** [mapsforge/mapsforge#1039]
See attached screenshots.

At zoom levels 6 & 8, London appears, using either InternalRenderTheme.DEFAULT or InternalRenderTheme.OSMARENDER.

![6](https://user-images.githubusercontent.com/8626721/36977307-9853c1e8-2078-11e8-8d37-5141194b3ab1.PNG)
![8](https://user-images.githubusercontent.com/8626721/36977310-9887970c-2078-11e8-853c-c9acba811b74.PNG)

At zoom level 7, it does not.

![7](https://user-images.githubusercontent.com/8626721/36977309-986ffb7e-2078-11e8-8d93-5794be3fac7c.PNG)

I've poured over the style files and I cannot see an obvious reason why this might be, so my conclusion is that it must be an issue with the code?

**Comment by devemux86** [comment]
Is it about the label?
And is it with regular rendering or [LabelLayer](https://github.com/mapsforge/mapsforge/blob/master/docs/LabelLayer.md)?
Can enable also map tiles to see if the missed label is due to tile grid calculations.

For questions and until a bug is found please use our [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by ludwigb** [comment]
I think to understand what is happening you need to understand how the
labelling algorithm works.

It starts out as one tile, trying to put as many labels as possible onto
that tile according to the rules. So the 'always' and high priority ones
should show up on the first tile you render.
Some labels will overlap the borders and the cache will remember which ones
these are when it comes to rendering that tile.
Since these labels are already half drawn (on the first tile), they _must_
be drawn onto the tile onto which they overlap (otherwise cut-off labels).

So, this is the reason for the somewhat nondeterministic appearance of
labels: it depends which tile you start out from.

Now, with London you get the problem that there are many suburbs, boroughs
etc with their own labels. They have the habit of crowding out the LONDON
label if they get drawn first.

There is unfortunately no easy solution for this.

The main problem behind all this is that the LONDON label is attached to a
single point, which sits somewhere inside the London area. The only
solution I see would be to totally change that algorithm but it would have
to start from attaching the LONDON label to an area, rather than a point.
But OSM data is not structured that way, and computing the positioning of
such labels will be pretty complex as one would have to do a computation of
which areas overlap which tiles.

Workarounds might be (within the limit of the current algorithm): reduce
text size of labels (so less overlap and less conflict) or make other
labels appear later (at higher zoom levels).

Ludwig

**Comment by JackPGreen** [comment]
As requested I have raised a new topic for this on the discussion board here - https://groups.google.com/forum/#!topic/mapsforge-dev/my6NOeNyKJk

I've added a further reply also.
