### ISSUE TITLE
Getting NoSuchMethodError exception

### ISSUE THREAD

**Issue by nagesh-kashyap-r** [mapsforge/mapsforge#1056]
Hello,

I'm facing issue when loading offline maps
I followed instructions as in "**https://github.com/osmdroid/osmdroid/wiki/Mapsforge**"

This is the exception i got : 

**"java.lang.NoSuchMethodError: No static method setMaximumBufferSize(I)V in class Lorg/mapsforge/map/reader/ReadBuffer; or its super classes (declaration of 'org.mapsforge.map.reader.ReadBuffer'"**

Gradle :
    **compile "org.osmdroid:osmdroid-mapsforge:5.6.5@aar"
    compile 'org.mapsforge:mapsforge-map-android:0.9.1'
    compile 'org.mapsforge:mapsforge-map:0.9.1'
    compile 'org.mapsforge:mapsforge-themes:0.9.1'**

**Comment by devemux86** [comment]
That's related on how Osmdroid uses Mapsforge, so should ask them for their implementation.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by TomasJohansson** [comment]
> That's related on how Osmdroid uses Mapsforge, so should ask them for their implementation.

But it is difficult for osmdroid (and other users of your library) to support your new versions if you introduce breaking changes such as removing a method from a [published api](https://martinfowler.com/bliki/PublishedInterface.html).

In issue #994 git commit c755db6 you removed the method setMaximumBufferSize (which was setting the field MAXIMUM_BUFFER_SIZE) while instead introducing a new class Parameters with the field MAXIMUM_BUFFER_SIZE.

Was there a reason for deleting the method instead of trying to make it easier for other libraries to support new versions?
For example, doing something like this instead of deleting the method:

```java
@Deprecated
public static synchronized void setMaximumBufferSize(int maximumBufferSize) {
	Parameters.setMaximumBufferSize(maximumBufferSize);
}
```

Unfortunately, now it seems diffcult for osmdroid to support a later version of mapsforge.
Quoting THE main contributor of omsdroid regarding support for mapsforge:
"wasn't a straight forward update due to the api changes and no clear path forward"
https://github.com/osmdroid/osmdroid/issues/1265

Some more guidance from you in [your changelog](https://github.com/mapsforge/mapsforge/blob/master/docs/Changelog.md) might be helpful for everyone trying to upgrade

**Comment by devemux86** [comment]
We generally avoid to alter the public API unless there is need and that was one of those cases. Certainly there are no plans to support multiple code paths inside the library. Anyway the changelog is usually the right place to describe such changes.
