### ISSUE TITLE
Broken links in docs.

### ISSUE THREAD

**Issue by Gustl22** [mapsforge/mapsforge#1099]
Non working links:
In [CONTRIBUTING.md](https://github.com/mapsforge/mapsforge/blob/master/.github/CONTRIBUTING.md) not working: **[Project Conventions](https://github.com/mapsforge/mapsforge/blob/master/.github/docs/Project-Conventions.md)**

In [Project Conventions](https://github.com/mapsforge/mapsforge/blob/master/docs/Project-Conventions.md) not working: **[Code Conventions for the Java Programming Language](https://www.oracle.com/technetwork/java/codeconv-138413.html)**
May replace with [Google Guidlines](https://google.github.io/styleguide/javaguide.html) as [Java Guidlines](https://www.oracle.com/technetwork/java/codeconvtoc-136057.html) are outdated.

May think about moving CONTRIBUTING.md to docs.
And insert the project conventions in contributing? Or move some paragraphs to project-conventions e.g. syntax indentation.

**Comment by devemux86** [comment]
`CONTRIBUTING.md` was introduced in `.github` subfolder, because back then GitHub showed it when creating new issues. Apparently the workflow seems broken now. :slightly_frowning_face: 

Regarding the links, they can be updated.
Note that the "follow the conventions you already see in the code" has precedence over external guides.
