### ISSUE TITLE
Add kinetic scrolling to the MapView

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#219]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on January 07, 2012 17:07:11_

Currently the map stops immediately when a move gesture is aborted. We should also support for kinetic scrolling, where the map is moved for a small time with a configurable attenuation.

This issue was originally part of issue 19 .

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=219_

**Comment by devemux86** [comment]
Closed as part of #688.

**Comment by devemux86** [comment]
There is have an artifact with current fling.

We scroll (pan) the map and stop but keeping touching for 1-2", then on lift up the map moves a bit more (an additional ```onFling``` event).

That's not expected behavior, users would not consider that action sequence as fling (but as scroll), so the map should be steady at the end.

**Comment by schildbach** [comment]
I cannot reproduce this on 11563db, can you maybe record a video?
