### ISSUE TITLE
More control on pathText

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#473]
_From [tartami...@gmail.com](https://code.google.com/u/115560783500310858875/) on December 26, 2013 16:45:49_

Right now we basically have no control on where pathText is rendered. I'd like being able to control the distance between repetitions.
Also an offset from the path (DY) would prevent unpleasing overlaps with the underlying path that is typically a road with some thickness.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=473_

**Comment by devemux86** [comment]
Reopening for checking the possibility of repeat options.

**Comment by ludwigb** [comment]
I have added repeat, repeat-start and repeat-gap to the pathText options. Since we are changing the RenderTheme we should also be increasing the version number, this has no effect on existing code or renderthemes. 

The code is probably roughly correct, but not really tested. There is some effect as to label appearance, but some things might not be quite as expected. 

There is RenderThemeV5 in Samples which sets, pretty arbitrarily, some of the new options. With some of the settings we seem to be getting cut-off labels again, a result of removing the safety margins around the tile borders. 

Would very much like that those requesters test this a bit and see if it does what they need. 

Another option is rotate (for consistency, but nothing is implemented), the meaning of rotate is if the label is to be rotated when the map is rotated, which we do not yet have.

**Comment by devemux86** [comment]
Thanks, I pushed some improvements.
The `repeat` option is by default `false`, don't we want it `true`?

I don't understand the changes in rendertheme-v5.xml.
In `waterway=stream|canal` why the need to add `repeat=false` (considering the default)?
Also in `highway` rules, there is addition of `repeat-start` / `repeat-gap` without enabling the `repeat` option.

About rotation, path texts will not be rotated by their center, but rather change writing orientation based on angle but still on line.

**Comment by applantation** [comment]
Yes, repeat should of course be true. Then everything else makes more sense
as well.

One more note on repeat tag: as we draw tile by tile, the repeat option can
only be applied to each tile, so text on lines spanning multiple tiles will
still be repeated.

**Comment by devemux86** [comment]
It's also default false in `lineSymbol`, but that's an established behavior.
That's why I'm wondering what we should do here.

**Comment by ludwigb** [comment]
That is where the code was copied from. It is inconsistent, but for
compatibility sake I am against changing.

**Comment by devemux86** [comment]
+1
Will you make the change?

**Comment by ludwigb** [comment]
Was just in process to make change, then you beat me to it.

**Comment by devemux86** [comment]
No please proceed. :)
(I haven't changed anything yet)

**Comment by ludwigb** [comment]
???

commit c5ec849c0dfe9d88a0e537b34f3e7201c8076c55

Author: Emux <devemux86@gmail.com>

Date:   Sun Mar 20 11:11:06 2016 +0200


    RenderThemeV5: pathText repeat improvements #473

**Comment by devemux86** [comment]
I mean in `PathText` the `repeat` variable shouldn't have default value `true`?
Now it's `false`.

**Comment by ludwigb** [comment]
Sorry my fault, just saw your commit that stopped me pushing my commit, but
did not clearly see the changes you made.

pushed

**Comment by devemux86** [comment]
About render theme version, when do we increase it?
Between MF releases with tag changes?

**Comment by devemux86** [comment]
>pushed

@ludwigb did you push the commit?

**Comment by ludwigb** [comment]
Sent email before push was completed, clashed with other commits....pushed
now, sorry.

**Comment by devemux86** [comment]
@ludwigb I don't think we need the new `rotate` directive in `pathText`.

For `lineSymbol` it has meaning, but here the text (e.g. road labels) should always follow the line geometry (even if map is rotated).
