### ISSUE TITLE
Blurry symbols with Java

### ISSUE THREAD

**Issue by Tartamillo** [mapsforge/mapsforge#550]
I see that in Atlas symbols are often blurry.The problem is that symbol positioning is not pixel perfect so bitmap graphics get interpolated. See https://groups.google.com/forum/#!topic/mapsforge-dev/1YQb2pn3AvA for example pictures.

**Comment by devemux86** [comment]
I pushed a fix in dev, using translation with integers (instead of floats) in symbols drawing, trying to handle the pixel positioning better.

There is clearly an improvement in Java and as a matter of fact in Android too.

We need to test it, for not causing other issues.

Before the fix.
![before](https://cloud.githubusercontent.com/assets/3484020/6199937/ab3513c2-b468-11e4-878c-59ab4bb4f6ee.png)

After the fix.
![after](https://cloud.githubusercontent.com/assets/3484020/6199939/aef58410-b468-11e4-9251-9f2bc13fad72.png)

**Comment by devemux86** [comment]
I pushed a fix in dev regarding the blurry symbols.

It improves clearly the drawing in Java and in Android too,
but it needs testing.

I have attached some images in the relevant issue 550 
<https://github.com/mapsforge/mapsforge/issues/550>.

-- 
Emux
Cruiser <http://wiki.openstreetmap.org/wiki/Cruiser> - Atlas 
<http://wiki.openstreetmap.org/wiki/Atlas_%28navigation_application%29>
