### ISSUE TITLE
MapDataStore extensibility

### ISSUE THREAD

**Issue by nickw1** [mapsforge/mapsforge#668]
In order for third-party authors to be able to write their own classes implementing MapDataStore in separate packages, it would be useful to make the PoiWayBundle class and the constructors for Way and PointOfInterest public (so that PoiWayBundle, Way and PointOfInterest objects can be created when parsing data)

**Comment by devemux86** [comment]
Are these the only needed for making ```MapDataStore``` usable in external packages?
e.g. the ```MapReadResult``` ?

**Comment by ludwigb** [comment]
I agree that MapReadResult should become a public interface to allow others
to build their own data sources.

I think the construction with the MapReadResult and MapReadResultBuilder
was mainly to ensure privacy/immutability. So if the MapReadResult becomes
a public interface the MapReadResultBuilder can essentially go/be folded
into a single class.

Ludwig

**Comment by devemux86** [comment]
I pushed the above arrangements.

@ludwigb can you explain what do you mean with becoming interface?

**Comment by nickw1** [comment]
Thanks for this.

**Comment by ludwigb** [comment]
@ludwigb <https://github.com/ludwigb> can you explain what do you mean with
becoming interface?

I think the main reason for having the MapReadResultBuilder (instead of
just having the MapReadResult) was to make the data in the MapReadResult
kind of immutable and private. With the MapReadResultBuilder being public
this does not exist anymore, so technically there is also no reason to have
these two classes separate.

My idea was to move the MapDataStore (interface) and all classes used by it
(but without implementation, that would make it a MapReadResult interface
class) into the mapsforge-map module.

Then have in the mapsforge-map-reader module only the stuff that reads from
our map file. That would allow us/other developers to build different data
stores (e.g. sqlite based) and use them with mapsforge without having to
also include the map file stuff.

It would provide a clean way of experimenting with new types of data store
(no change in mapsforge libraries required).

If we went this way, in a second step I would suggest making the
MapDataStore interface a little bit more generic, e.g. providing a method
that returns data not for a tile, but for a set of tiles or a bbox: that
would make it much easier to implement label layers (=> rotation,
multi-lingual rendering).

Ludwig

**Comment by devemux86** [comment]
@ludwigb I agree with that concept, it sounds more modular.

**Comment by ludwigb** [comment]
I reopen this for the refactoring I had suggested above.

**Comment by ludwigb** [comment]
With ceb11590eb20c7cd2247a I refactored MapDataStore interface and related classes to reside in mapsforge-map datastore. This removes the need to pull in all the MapFile related implementation for those who want to implement their own map store. 

To implement a MapDataStore the reader component will have to supply a MapReadResult, but the implementation is not bound to the MapReadResultBuilder anymore.

A number of tests had to move to mapsforge-map-awt as they use AwtGraphicsFactory as the circular dependencies were getting too complicated. The actual tests have not changed.

**Comment by devemux86** [comment]
Analyzing the refactoring:

- We should probably rename ```MapReadResultBuilder``` to ```MapFileReadResultBuilder``` since it's now connected to ```MapFileReadResult```

- Regarding modules dependencies, we could simplify them (tested on Maven):
  - ```map``` depends on ```core```
  - ```map-reader``` depends on ```map```
  - ```map-android``` and ```map-awt``` depend on ```map-reader```

**Comment by ludwigb** [comment]
+1 for renaming MapFileResultBuilder, I had actually thought of removing it
altogether, because IMHO it does not really serve a great purpose (the
functionality can be folded into MapFileReadResult).

The dependency chain is already like this in gradle, if the additional
dependencies can be removed for maven as well, the better.

**Comment by devemux86** [comment]
I removed ```MapReadResultBuilder``` putting its actions in ```MapFileReadResult```.

(I updated also Maven mapsforge dependencies, though comparing them with Gradle I find differences)

**Comment by ludwigb** [comment]
Will move MultiMapDataStore also into the mapsforge-map library, it is not specific to map file reading.

**Comment by ludwigb** [comment]
I just added an example of a simple non-map DataStore to the Samples app. The difference to overlays is that the data is rendered on the tiles, just as if it came from a map file. 
Potential usages of this: updates of map data while at the same time using a base map, but careful as tiles will be cached with potentially stale data.

**Comment by devemux86** [comment]
Now ```MapFileReadResult``` constructor can call its super (```MapReadResult```) (better have diamond operator in both lists).

**Comment by ludwigb** [comment]
I guess we can get rid of MapFileReadResult entirely, by moving the
addPoiWayBundle method up into MapReadResult and also the PoiWayBundle into
mapsforge-map.

?

**Comment by devemux86** [comment]
>I guess we can get rid of MapFileReadResult entirely, by moving the addPoiWayBundle method up into MapReadResult and also the PoiWayBundle into mapsforge-map.

+1

**Comment by devemux86** [comment]
About the samples example: interesting concept! :+1:

**Comment by ludwigb** [comment]
>
> About the samples example: interesting concept! [image: :+1:]
>

I was just thinking about making this a bit more useful by adding it to
diagnostics: instead of writing a circle into the tile, we could write the
order number in which tiles are generated into the middle (plus timestamp).
Requires change of rendertheme used.

**Comment by applantation** [comment]
On 13 September 2015 at 16:19, Emux <notifications@github.com> wrote:

> I guess we can get rid of MapFileReadResult entirely, by moving the
> addPoiWayBundle method up into MapReadResult and also the PoiWayBundle into
> mapsforge-map.
>
> +1
>

done

**Comment by devemux86** [comment]
@ludwigb do we have more work on that?
