### ISSUE TITLE
Android gestures

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#688]
- [x] Scroll (pan)
- [x] Scale
- [x] Scale with focus
- [x] Quick scale (double tap + swipe)
- [x] Fling (kinetic scroll)
- [x] Double tap (zoom with focus)
- [x] Tap (overlay)
- [x] Long press (overlay)

**Comment by schildbach** [comment]
Here is some takeaways from my PR #687:

- We should remove animations from MapViewPosition entirely. UI animations are very specific to the platform in use. They have their specific look and feel and usually there are already classes to support them. Also threading is handled differently: e.g. on Android you'd prefer to use a Handler rather than spawning a thread.

- The remaining jaggies are due to the fact MapViewPosition keeps a `byte zoomLevel` and a `float scaleFactor` separately. That makes it difficult to get simultaneous zooming and panning right. We should think about getting rid of the zoomLevel and only use one single `float scaleFactor` (maybe rename it to zoomFactor). Of course we can still keep the old methods that deal with the byte values for backwards compatibility.

**Comment by devemux86** [comment]
1. Not a bad idea, though we'll need to transfer functionality to android / awt modules.

2. Moving from byte to float is like steplessly variable zoom levels #75 ?

**Comment by devemux86** [comment]
With 94623e5def57f372143e927758f02ca8480bb599 I pushed a set of various additions / improvements / fixes with the new Mapsforge gesture system.

Any artifacts were mostly eliminated with proper handling of the scroll / fling and scale gestures interaction.

Of course thorough testing is advised as always to check where we're standing.

**Comment by devemux86** [comment]
Thilo had expressed some [thoughts](https://github.com/mapsforge/mapsforge/issues/183#issuecomment-61951281) some years ago, regarding the panning threshold we had active until recently.

How do you find the new Mapsforge gesture handling, do we need a panning threshold?

**Comment by schildbach** [comment]
I believe the stock GestureDetector handles this all for us already, including quirks for old devices with a bad screen digitizer.

All my test devices certainly do not need an (additional) panning threshold.

**Comment by devemux86** [comment]
@schildbach thanks for the feedback.

Those were indeed old Android days, I just want to make sure we have implemented all the right way.
