### ISSUE TITLE
Sample app crashing randomly with TombStone errors

### ISSUE THREAD

**Issue by spyhunter99** [mapsforge/mapsforge#703]
I'm getting this a lot

18): Revision: '9'
I/DEBUG   ( 2218): pid: 7497, tid: 7539, name: pool-5-thread-5  >>> org.mapsforge.applications.android.samples <<<
I/DEBUG   ( 2218): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000180

I've seen this with memory corruption or bad points with native code. Anyone else seeing this? I just downloaded and built the sample app off of the main branch 10 minutes ago

**Comment by spyhunter99** [comment]
seems to happen near coast lines

**Comment by applantation** [comment]
Obviously we do not see this this often, so a bit more context is really
required.
Which Sample app are you running? On what Android version/device etc.

Ludwig

**Comment by spyhunter99** [comment]
"Mapsforge Samples", "Map Viewer Renderertheme V4" and many of the other sample activities. Andrpid 4.4.2. Samsung tab s

**Comment by spyhunter99** [comment]
More log output here:
http://pastebin.com/3wuiHjBD

**Comment by devemux86** [comment]
Which Sample, from ```master``` or ```dev``` branch?

Because they have some differences (that could cause issues):
- ```dev``` has enabled hardware acceleration
- ```dev``` has enabled multi threaded rendering

@ludwigb to avoid future user confusion I'm thinking we should revert them to ```master``` stable settings, until they are production ready.

**Comment by ludwigb** [comment]
I think we should by default set the thread number to 1. The problem is
that I now understand that multi-threading will always cause OOMs simply
because we need too much memory to read multiple tiles at the same time.
The problem is not really with the multi-threaded code, but with the
reading operation which has to read all data for a tile in one go.

With hardware acceleration, I think we should leave it on in dev, it is
something that helps us testing.

Ludwig

**Comment by spyhunter99** [comment]
I'm on master.

**Comment by spyhunter99** [comment]
Also crashing on tag 0.5.2rc3 and on 0.5.2. 0.5.1 does work, however the map flickers a bit when panning.

by the way, i really like this project and much respect for using maven.

**Comment by devemux86** [comment]
Flickering should only happen when HA is on, have you enabled it?
(We had fixed some HA issues in 0.5.2-rc1)

>much respect for using maven

:+1:

**Comment by spyhunter99** [comment]
Ok more context. It seems to crash when i pan in the area with a military base on it. maybe it's the large number of mini tanks that get rendered on screen?

**Comment by spyhunter99** [comment]
damn 0.5.1 just crashed again. i'll play around with this later tonight

**Comment by applantation** [comment]
I do not think it has anything to do with the complexity of the symbol,
they are rendered into a bitmap only once and then just reduplicated. The
screen does not really care which pixels are on.

It could have something to do with the clean up operation of the bitmaps,
that has been a problem in the past and some devices seem to be more
susceptible to a crash then others.

Do you have any other device to play with? While I have seen skia crashes
in the past, I have not seen them that frequently. So either it is
something specific to your device or specific what your are doing.

Ludwig

**Comment by spyhunter99** [comment]
I just tried on an x86 box I have. I'm also getting a different tombstone, Floating Point Exception this time

**Comment by spyhunter99** [comment]
I just built from source and ran on x86 android and couldn't reproduce. not sure what the root cause was but it seems ok now.
