### ISSUE TITLE
TouchSlop

### ISSUE THREAD

**Issue by NamakeHU** [mapsforge/mapsforge#721]
Please make this variable public and not final:
private final float mapMoveDelta;

You set the value from TouchSlop and the value (16) is too much:
this.mapMoveDelta = viewConfiguration.getScaledTouchSlop(); 

Let me control this value please.
Thanks.

**Comment by devemux86** [comment]
This is related to old Mapsforge [code](https://github.com/mapsforge/mapsforge/blob/0.5.2/mapsforge-map-android/src/main/java/org/mapsforge/map/android/input/TouchEventHandler.java).

We rewrote the Android touch gestures in latest 0.6 release (see #688).

**Comment by NamakeHU** [comment]
Ok, but my problem is still exist. 
When you starting to scroll the map, it begins with a jump, because there are too many pixels deadzone. It's annoying.
I'd like to control this deadzone.

**Comment by devemux86** [comment]
Does [Samples](https://github.com/mapsforge/mapsforge/blob/master/docs/Downloads.md) app of Mapsforge 0.6 has that behavior?
I cannot see it, can you explain better what you mean?

BTW now we use the default Android gesture system for handling the map view interaction.

**Comment by NamakeHU** [comment]
Yes it does.

So, when I touch the screen and slowly begin to move my finger to scroll the map, it does not scrolling until reaching the deadzone limit (16 pixels) and then the map jumps at least as many pixels. Beyond that the map follows my finger movement correctly. If I do the swipe motion faster, the jump is more visible because the bigger delta movement at the start after reaching the deadzone limit.

(Maybe a solution that reset the delta value to zero when the scrolling is actually starting.
Or if possible decreasing the deadzone to 2 pixels, what I like to do.)

**Comment by devemux86** [comment]
Base 'touch slop' value is ```8dp```, any actual difference is because of display density.
That's something a little deep in Android configuration and set per device.

It may be nice to have it variable, though I don't see if it's feasible (it's only read on ```View``` initialization).
We should certainly avoid writting again custom gesture implementations - that was quite unmanageable in the past.

Nevertheless if anyone has any solution to alter such core Android configuration values, we can see it.

*And to think that until recently we had even additional panning [threshold](https://github.com/mapsforge/mapsforge/issues/688#issuecomment-143412827).*

**Comment by NamakeHU** [comment]
I see. :(
Unfortunately on my phone (Xperia Mini) the touch slop value is 20. I don't know why, but it is way too much to ignore.
