### ISSUE TITLE
Hillshading

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#923]
Hillshading from digital elevation model data like [HGT](http://wiki.openstreetmap.org/wiki/SRTM#Format) format.

**Comment by devemux86** [comment]
See PR #922 by @usrusr.

**Comment by devemux86** [comment]
On Desktop Samples the 1st argument can be used as `dem` folder.

Will leave the issue open for monitoring further hillshading improvements.

**Comment by demiantres** [comment]
The hillshading algorithm produces visible seams along HGT file borders:

![mfbound](https://user-images.githubusercontent.com/5980561/30467982-b7c7d968-99e8-11e7-9d90-0ca55e991968.png)

**Comment by usrusr** [comment]
Visible seams in rough areas are known (interpolation artifacts: the interpolator assumes that the neighboring pixel outside the texture is the same color as the closest available, the dark part at the northern hill is one of those), But the dark line in the lowlands must be something different. 

Except if the screenshot is from a build based on the stale state of my morehills branch, then it is a known error in my attempts of fixing the interpolation issue (which is why the morehills has no PR).
