### ISSUE TITLE
Increase MapFile storage flexibility

### ISSUE THREAD

**Issue by linuskr** [mapsforge/mapsforge#982]
The current MapFile's dependence on File is unnecessarily limiting. The RandomAccessFile could be replaced with a FileChannel, which extends the backing storage to not only actual files, but also DocumentFiles. This allows usage of the Storage Access Framework with all its benefits.

**Comment by devemux86** [comment]
Actually it's implemented according to common needs. Everything can be improved further and being an open source library, any contributions are always welcome. :slightly_smiling_face: 

Note: since the library is cross-platform, need to maintain compatibility with all supported OS, e.g. Android, Desktop, etc.
So would need extensions in separate modules for each one's specific API.

**Comment by linuskr** [comment]
I did not intend to come across as hostile, i just wanted to show the advantages of such a change over the current implementation. The suggested change should be compatible with all normal java implementations. If there is interest, i can try to write a pull request.

**Comment by devemux86** [comment]
> If there is interest, i can try to write a pull request.
:+1:

**Comment by devemux86** [comment]
Closed via #986.
